{% set name = "marshmallow" %}
{% set version = "3.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/marshmallow-{{ version }}.tar.gz
  sha256: 0822c3701de396b51d3f8ac97319aea5493998ba4e7d0e4c05f6fce7777bf3a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - flit-core <4
    - pip
  run:
    - python >={{ python_min }}
    - packaging >=17.0

test:
  requires:
    - pip
    - pytest
    - simplejson
    - pytz
    - python-dateutil
    - python {{ python_min }}
  imports:
    - marshmallow
  source_files: tests/*.py
  commands:
    - python -m pytest tests
    - pip check

about:
  home: https://github.com/marshmallow-code/marshmallow
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - NOTICE
  summary: A lightweight library for converting complex datatypes to and from native Python datatypes.
  description: |
    marshmallow is an ORM/ODM/framework-agnostic library for
    converting complex datatypes, such as objects, to and from
    native Python datatypes.
  doc_url: https://marshmallow.readthedocs.io/en/latest/
  dev_url: https://github.com/marshmallow-code/marshmallow/

extra:
  recipe-maintainers:
    - hajapy
    - rth
    - frol
    - igortg
    - carlodri
    - mariusvniekerk
    - xylar
