{% set name = "marshmallow" %}
{% set version = "3.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marshmallow-{{ version }}.tar.gz
  sha256: 98d8827a9f10c03d44ead298d2e99c6aea8197df18ccfad360dae7f89a50da2e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - flit-core <4
    - pip
  run:
    - python >=3.9
    - packaging >=17.0

test:
  requires:
    - pip
    - pytest
    - simplejson
    - pytz
    - python-dateutil
  imports:
    - marshmallow
  source_files: tests/*.py
  commands:
    - python -m pytest tests
    - pip check

about:
  home: http://github.com/marshmallow-code/marshmallow
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - NOTICE
  summary: A lightweight library for converting complex datatypes to and from native Python datatypes.
  description: |
    marshmallow is an ORM/ODM/framework-agnostic library for
    converting complex datatypes, such as objects, to and from
    native Python datatypes.
  doc_url: http://marshmallow.readthedocs.io/en/latest/
  dev_url: https://github.com/marshmallow-code/marshmallow/

extra:
  recipe-maintainers:
    - hajapy
    - rth
    - frol
    - igortg
    - carlodri
    - mariusvniekerk
    - xylar
