{% set name = "marshmallow" %}
{% set version = "3.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2aaaab4f01ef4f5a011a21319af9fce17ab13bf28a026d1252adab0e035648d5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging

test:
  requires:
    - pip
    - pytest
    - simplejson
    - pytz
    - python-dateutil
  imports:
    - marshmallow
  source_files: tests/*
  commands:
    - python -m pytest tests
    - pip check

about:
  home: http://github.com/marshmallow-code/marshmallow
  license: MIT
  license_file: LICENSE
  summary: A lightweight library for converting complex datatypes to and from native Python datatypes.

  description: |
    marshmallow is an ORM/ODM/framework-agnostic library for
    converting complex datatypes, such as objects, to and from
    native Python datatypes.
  doc_url: http://marshmallow.readthedocs.io/en/latest/
  dev_url: https://github.com/marshmallow-code/marshmallow/

extra:
  recipe-maintainers:
    - hajapy
    - rth
    - frol
    - igortg
    - carlodri
    - mariusvniekerk
    - xylar
