{% set name = "marshmallow" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe31ac05fbde972909a752d12b808cbbc15a50ed0a692410e1b227ff10b483ff

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - marshmallow

about:
  home: http://github.com/marshmallow-code/marshmallow
  license: MIT
  license_file: LICENSE
  summary: 'A lightweight library for converting complex datatypes to and from native Python datatypes.'

  description: |
    marshmallow is an ORM/ODM/framework-agnostic library for
    converting complex datatypes, such as objects, to and from
    native Python datatypes.
  doc_url: http://marshmallow.readthedocs.io/en/latest/
  dev_url: https://github.com/marshmallow-code/marshmallow/

extra:
  recipe-maintainers:
    - hajapy
    - rth
    - frol
    - igortg
    - carlodri
