travis:
  secure:
    BINSTAR_TOKEN: BfEyshJewWCDDpa2ipcEZ0IO5ZL/FXe7dcOfIOl+T9ad1+rB0oj2iekjh4FDoIZVnx6eM+ot8J6OfOFmplrknidvPrDOkpy/LuSASYeFRMC5vZJTEbZRrbFHSi4Niwb7xFZrwXfAmSjD12Of5Pg3bJIO1UZ9bnl5/3mOtMRXwNdlSSapePEJEm4YPzjADfipKa2hg2qV2mjQs+nRNmC0iYlRxwEyz5a5j97dbJ8228hq0lR4Q03GTnWRsUP6Lbh/nJ/DXOBjUbr9ac/Js04IIvcVBD9oAGEjSEdnZqGHG8er8voI/esIOd/KVzLkM2LuXuArgm2MijXmS1seUpt4OKy1GIXoG0PKM0Jp3VlDJYLfgckoRk9KQyuhopLwl3FvKTXQu99M8ztceUq/mLz8y4/mj1dX+tpcSCMugU1Y4TBW/S1vMaaKTIcoMZkBwDD5LGF5vOcmyODHQDSaYe5c02m8pcET4s4OqIVStf3pi8qCKWzervmgA2wpt0hnsQDtnWoau6K+8zu7rTS6FyZ+jKS24MBK1mI6uwjOvIgvFiFF+E0pzfFZbttURgs2AKtGDMWSjV6RznlFm6UJLjK5u9fhizP4iEcNDDOLXAbeJEiSdoFO/1l9hrBV8li8pPE23rPOioA+pvu2kGZ7fBYEOQufAc3JHIM6EzUkuDFnxcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
